apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper-on-eks
spec:
  selector:
    matchLabels:
      name: scraper-on-eks
  template:
    metadata:
      labels:
        name: scraper-on-eks
    spec:
      containers:
        - name: app
          image: ghcr.io/mbrydak/overengineered-solutions:main
          ports:
            - containerPort: 5000